[tasks.setup-mac]
description = "Deploy macOS dotfiles with GNU Stow"
run = [
  'stow -R zsh -t "$HOME"',
  'stow -R mise -t "$HOME/.config/mise"',
  'stow -R vscode -t "$HOME/Library/Application Support/Code/User"',
  'stow -R nvim -t "$HOME/.config/nvim"',
  'stow -R tmux -t "$HOME/.config/tmux"',
  'stow -R herdr -t "$HOME/.config/herdr"',
  'stow -R opencode -t "$HOME/.config/opencode"',
  'stow -R ghostty -t "$HOME/.config/ghostty"',
  'stow -R aerospace -t "$HOME/.config/aerospace"',
]

[tasks.setup-linux]
description = "Deploy Linux dotfiles with GNU Stow"
run = [
  'stow -R zsh -t "$HOME"',
  'stow -R mise -t "$HOME/.config/mise"',
  'stow -R vscode -t "$HOME/.config/Code/User"',
  'stow -R nvim -t "$HOME/.config/nvim"',
  'stow -R tmux -t "$HOME/.config/tmux"',
  'stow -R herdr -t "$HOME/.config/herdr"',
  'stow -R opencode -t "$HOME/.config/opencode"',
  'stow -R ghostty -t "$HOME/.config/ghostty"',
]

[tasks."karabiner:build"]
description = "Build Karabiner configuration"
run = "cd karabiner && deno task build"
